development:
  adapter: postgresql
  encoding: unicode
  database: radbear_mobile_development

test:
  adapter: postgresql
  encoding: unicode
  database: radbear_mobile_test

production:
  adapter: postgresql
  encoding: unicode
  database: radbear_mobile_production