test:
  bucket: <%= ENV['S3_BUCKET'] %>
  access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['S3_ACCESS_KEY_ID'] %>

development:
  bucket: <%= ENV['S3_BUCKET'] %>
  access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['S3_ACCESS_KEY_ID'] %>

production:
  bucket: <%= ENV['S3_BUCKET'] %>
  access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['S3_ACCESS_KEY_ID'] %>